# Generated by Django 4.2.3 on 2023-07-06 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'visualizar Catálogo de Vehículos'),)},
        ),
    ]
