# Generated by Django 4.2.3 on 2023-07-06 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_alter_vehiculo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'visualizar Catálogo de Vehículos'), ('add_vehiculomodel', 'añade vehiculo'))},
        ),
    ]
